### ISSUE TITLE
Cant seem to set it up correctly

### ISSUE THREAD

**Issue by Yearlll** [Bytezz/godot-polyhaven-import#1]
this looks so good! but I just cant seem to be able to set it up and have it show up correctly or at all, I know this is probably me being stupid, but can you please add a tutorial on how to import it? thanks :)

**Comment by Bytezz** [comment]
<details>
<summary>Download from "AssetLib"</summary>

![Screenshot from 2023-11-08 13-16-31](https://github.com/Bytezz/godot-polyhaven-import/assets/25850701/97ca71e6-011c-41de-b851-da2af808c6e6)
![Screenshot from 2023-11-08 13-16-40](https://github.com/Bytezz/godot-polyhaven-import/assets/25850701/6e950231-1f72-415a-9110-8d6cabfe5a46)

</details>

<details>
<summary>Install everything</summary>

![Screenshot from 2023-11-08 13-16-52](https://github.com/Bytezz/godot-polyhaven-import/assets/25850701/0e1ad6ed-12a7-4ef8-88de-148cf6fb181c)

</details>

<details>
<summary>Enable inside Project Settings > Plugins</summary>

![Screenshot from 2023-11-08 13-17-07](https://github.com/Bytezz/godot-polyhaven-import/assets/25850701/82971d62-7296-458f-a409-0c22ec1fc34e)

</details>

<details>
<summary>Choose what you want to import and will be automatically imported inside the project</summary>

![Screenshot from 2023-11-08 13-17-30](https://github.com/Bytezz/godot-polyhaven-import/assets/25850701/efb02b70-fa74-482f-828b-ca0363aab2f8)
![Screenshot from 2023-11-08 13-18-37](https://github.com/Bytezz/godot-polyhaven-import/assets/25850701/1cb69768-060f-4944-b8b6-1814d785f02a)

</details>

**Comment by Yearlll** [comment]
That's what I tried but it doesn't seem to show up in the asset library (at least when using the newest version of godot)

**Comment by Bytezz** [comment]
> (at least when using the newest version of godot)

This works only with Godot 3.x, not Godot 4. What version are you using?

**Comment by Yearlll** [comment]
Ohhhh yeah that makes sense, I was using godot 4 in hopes of using it with 4's new global illumination options, anyways... thanks for the help!

**Comment by Bytezz** [comment]
I would like to do a version for Godot 4, but I'm not able to :/

**Comment by Bytezz** [comment]
@scienceiseverything, I've just ported it to Godot 4.x.
